version: "3.8"

networks:
    boilerplate:
      driver: bridge

services: 
    api:
        build: 
            context: .
            dockerfile: ./infrastructure/node/Dockerfile
        ports: 
            - 3000:3000
        volumes: 
            - .:/usr/app
        networks:
          - boilerplate
